PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTVARVC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTVARVC-VARNAME .
    FIELD ZTVARVC-TYPE .
    FIELD ZTVARVC-NUMB .
    FIELD ZTVARVC-ENDDA .
    FIELD ZTVARVC-BEGDA .
    FIELD ZTVARVC-TABLENAME .
    FIELD ZTVARVC-FIELDNAME .
    FIELD ZTVARVC-CREATEDBY .
    FIELD ZTVARVC-CREATEDON .
    FIELD ZTVARVC-CHANGEDBY .
    FIELD ZTVARVC-CHANGEDON .
    FIELD ZTVARVC-SIGN .
    FIELD ZTVARVC-OPTI .
    FIELD ZTVARVC-LOW .
    FIELD ZTVARVC-HIGH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTVARVC-VARNAME .
    FIELD ZTVARVC-TYPE .
    FIELD ZTVARVC-NUMB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
