*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZADF_V_CONFIG...................................*
FORM GET_DATA_ZADF_V_CONFIG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADF_CONFIG WHERE
(VIM_WHERETAB) .
    CLEAR ZADF_V_CONFIG .
ZADF_V_CONFIG-MANDT =
ZADF_CONFIG-MANDT .
ZADF_V_CONFIG-INTERFACE_ID =
ZADF_CONFIG-INTERFACE_ID .
ZADF_V_CONFIG-INTERFACE_TYPE =
ZADF_CONFIG-INTERFACE_TYPE .
ZADF_V_CONFIG-SAS_KEY =
ZADF_CONFIG-SAS_KEY .
ZADF_V_CONFIG-URI =
ZADF_CONFIG-URI .
ZADF_V_CONFIG-SERVICE_TYPE =
ZADF_CONFIG-SERVICE_TYPE .
<VIM_TOTAL_STRUC> = ZADF_V_CONFIG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADF_V_CONFIG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADF_V_CONFIG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADF_V_CONFIG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADF_CONFIG WHERE
  INTERFACE_ID = ZADF_V_CONFIG-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZADF_CONFIG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADF_CONFIG WHERE
  INTERFACE_ID = ZADF_V_CONFIG-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADF_CONFIG.
    ENDIF.
ZADF_CONFIG-MANDT =
ZADF_V_CONFIG-MANDT .
ZADF_CONFIG-INTERFACE_ID =
ZADF_V_CONFIG-INTERFACE_ID .
ZADF_CONFIG-INTERFACE_TYPE =
ZADF_V_CONFIG-INTERFACE_TYPE .
ZADF_CONFIG-SAS_KEY =
ZADF_V_CONFIG-SAS_KEY .
ZADF_CONFIG-URI =
ZADF_V_CONFIG-URI .
ZADF_CONFIG-SERVICE_TYPE =
ZADF_V_CONFIG-SERVICE_TYPE .
    IF SY-SUBRC = 0.
    UPDATE ZADF_CONFIG ##WARN_OK.
    ELSE.
    INSERT ZADF_CONFIG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADF_V_CONFIG-UPD_FLAG,
STATUS_ZADF_V_CONFIG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADF_V_CONFIG.
  SELECT SINGLE * FROM ZADF_CONFIG WHERE
INTERFACE_ID = ZADF_V_CONFIG-INTERFACE_ID .
ZADF_V_CONFIG-MANDT =
ZADF_CONFIG-MANDT .
ZADF_V_CONFIG-INTERFACE_ID =
ZADF_CONFIG-INTERFACE_ID .
ZADF_V_CONFIG-INTERFACE_TYPE =
ZADF_CONFIG-INTERFACE_TYPE .
ZADF_V_CONFIG-SAS_KEY =
ZADF_CONFIG-SAS_KEY .
ZADF_V_CONFIG-URI =
ZADF_CONFIG-URI .
ZADF_V_CONFIG-SERVICE_TYPE =
ZADF_CONFIG-SERVICE_TYPE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADF_V_CONFIG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADF_V_CONFIG-INTERFACE_ID TO
ZADF_CONFIG-INTERFACE_ID .
MOVE ZADF_V_CONFIG-MANDT TO
ZADF_CONFIG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADF_CONFIG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADF_CONFIG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADF_CONFIG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZADF_V_EVPOLICY.................................*
FORM GET_DATA_ZADF_V_EVPOLICY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADF_EHUB_POLICY WHERE
(VIM_WHERETAB) .
    CLEAR ZADF_V_EVPOLICY .
ZADF_V_EVPOLICY-MANDT =
ZADF_EHUB_POLICY-MANDT .
ZADF_V_EVPOLICY-INTERFACE_ID =
ZADF_EHUB_POLICY-INTERFACE_ID .
ZADF_V_EVPOLICY-POLICY =
ZADF_EHUB_POLICY-POLICY .
<VIM_TOTAL_STRUC> = ZADF_V_EVPOLICY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADF_V_EVPOLICY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADF_V_EVPOLICY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADF_V_EVPOLICY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADF_EHUB_POLICY WHERE
  INTERFACE_ID = ZADF_V_EVPOLICY-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZADF_EHUB_POLICY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADF_EHUB_POLICY WHERE
  INTERFACE_ID = ZADF_V_EVPOLICY-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADF_EHUB_POLICY.
    ENDIF.
ZADF_EHUB_POLICY-MANDT =
ZADF_V_EVPOLICY-MANDT .
ZADF_EHUB_POLICY-INTERFACE_ID =
ZADF_V_EVPOLICY-INTERFACE_ID .
ZADF_EHUB_POLICY-POLICY =
ZADF_V_EVPOLICY-POLICY .
    IF SY-SUBRC = 0.
    UPDATE ZADF_EHUB_POLICY ##WARN_OK.
    ELSE.
    INSERT ZADF_EHUB_POLICY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADF_V_EVPOLICY-UPD_FLAG,
STATUS_ZADF_V_EVPOLICY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADF_V_EVPOLICY.
  SELECT SINGLE * FROM ZADF_EHUB_POLICY WHERE
INTERFACE_ID = ZADF_V_EVPOLICY-INTERFACE_ID .
ZADF_V_EVPOLICY-MANDT =
ZADF_EHUB_POLICY-MANDT .
ZADF_V_EVPOLICY-INTERFACE_ID =
ZADF_EHUB_POLICY-INTERFACE_ID .
ZADF_V_EVPOLICY-POLICY =
ZADF_EHUB_POLICY-POLICY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADF_V_EVPOLICY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADF_V_EVPOLICY-INTERFACE_ID TO
ZADF_EHUB_POLICY-INTERFACE_ID .
MOVE ZADF_V_EVPOLICY-MANDT TO
ZADF_EHUB_POLICY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADF_EHUB_POLICY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADF_EHUB_POLICY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADF_EHUB_POLICY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZADF_V_MI_CONFIG................................*
FORM GET_DATA_ZADF_V_MI_CONFIG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADF_MI_CONFIG WHERE
(VIM_WHERETAB) .
    CLEAR ZADF_V_MI_CONFIG .
ZADF_V_MI_CONFIG-MANDT =
ZADF_MI_CONFIG-MANDT .
ZADF_V_MI_CONFIG-INTERFACE_ID =
ZADF_MI_CONFIG-INTERFACE_ID .
ZADF_V_MI_CONFIG-RESOURCE_ID =
ZADF_MI_CONFIG-RESOURCE_ID .
ZADF_V_MI_CONFIG-CLIENT_ID =
ZADF_MI_CONFIG-CLIENT_ID .
ZADF_V_MI_CONFIG-MI_NAME =
ZADF_MI_CONFIG-MI_NAME .
<VIM_TOTAL_STRUC> = ZADF_V_MI_CONFIG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADF_V_MI_CONFIG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADF_V_MI_CONFIG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADF_V_MI_CONFIG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADF_MI_CONFIG WHERE
  INTERFACE_ID = ZADF_V_MI_CONFIG-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZADF_MI_CONFIG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADF_MI_CONFIG WHERE
  INTERFACE_ID = ZADF_V_MI_CONFIG-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADF_MI_CONFIG.
    ENDIF.
ZADF_MI_CONFIG-MANDT =
ZADF_V_MI_CONFIG-MANDT .
ZADF_MI_CONFIG-INTERFACE_ID =
ZADF_V_MI_CONFIG-INTERFACE_ID .
ZADF_MI_CONFIG-RESOURCE_ID =
ZADF_V_MI_CONFIG-RESOURCE_ID .
ZADF_MI_CONFIG-CLIENT_ID =
ZADF_V_MI_CONFIG-CLIENT_ID .
ZADF_MI_CONFIG-MI_NAME =
ZADF_V_MI_CONFIG-MI_NAME .
    IF SY-SUBRC = 0.
    UPDATE ZADF_MI_CONFIG ##WARN_OK.
    ELSE.
    INSERT ZADF_MI_CONFIG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADF_V_MI_CONFIG-UPD_FLAG,
STATUS_ZADF_V_MI_CONFIG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADF_V_MI_CONFIG.
  SELECT SINGLE * FROM ZADF_MI_CONFIG WHERE
INTERFACE_ID = ZADF_V_MI_CONFIG-INTERFACE_ID .
ZADF_V_MI_CONFIG-MANDT =
ZADF_MI_CONFIG-MANDT .
ZADF_V_MI_CONFIG-INTERFACE_ID =
ZADF_MI_CONFIG-INTERFACE_ID .
ZADF_V_MI_CONFIG-RESOURCE_ID =
ZADF_MI_CONFIG-RESOURCE_ID .
ZADF_V_MI_CONFIG-CLIENT_ID =
ZADF_MI_CONFIG-CLIENT_ID .
ZADF_V_MI_CONFIG-MI_NAME =
ZADF_MI_CONFIG-MI_NAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADF_V_MI_CONFIG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADF_V_MI_CONFIG-INTERFACE_ID TO
ZADF_MI_CONFIG-INTERFACE_ID .
MOVE ZADF_V_MI_CONFIG-MANDT TO
ZADF_MI_CONFIG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADF_MI_CONFIG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADF_MI_CONFIG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADF_MI_CONFIG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZADF_V_O365CONF.................................*
FORM GET_DATA_ZADF_V_O365CONF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZO365_CONFIG WHERE
(VIM_WHERETAB) .
    CLEAR ZADF_V_O365CONF .
ZADF_V_O365CONF-MANDT =
ZO365_CONFIG-MANDT .
ZADF_V_O365CONF-INTERFACE_ID =
ZO365_CONFIG-INTERFACE_ID .
ZADF_V_O365CONF-INTERFACE_TYPE =
ZO365_CONFIG-INTERFACE_TYPE .
ZADF_V_O365CONF-SERVICE_TYPE =
ZO365_CONFIG-SERVICE_TYPE .
ZADF_V_O365CONF-IS_TRY =
ZO365_CONFIG-IS_TRY .
ZADF_V_O365CONF-CLIENT_ID =
ZO365_CONFIG-CLIENT_ID .
ZADF_V_O365CONF-RESOURCE_ID =
ZO365_CONFIG-RESOURCE_ID .
ZADF_V_O365CONF-AAD_INTERFACE_ID =
ZO365_CONFIG-AAD_INTERFACE_ID .
<VIM_TOTAL_STRUC> = ZADF_V_O365CONF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADF_V_O365CONF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADF_V_O365CONF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADF_V_O365CONF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZO365_CONFIG WHERE
  INTERFACE_ID = ZADF_V_O365CONF-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZO365_CONFIG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZO365_CONFIG WHERE
  INTERFACE_ID = ZADF_V_O365CONF-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZO365_CONFIG.
    ENDIF.
ZO365_CONFIG-MANDT =
ZADF_V_O365CONF-MANDT .
ZO365_CONFIG-INTERFACE_ID =
ZADF_V_O365CONF-INTERFACE_ID .
ZO365_CONFIG-INTERFACE_TYPE =
ZADF_V_O365CONF-INTERFACE_TYPE .
ZO365_CONFIG-SERVICE_TYPE =
ZADF_V_O365CONF-SERVICE_TYPE .
ZO365_CONFIG-IS_TRY =
ZADF_V_O365CONF-IS_TRY .
ZO365_CONFIG-CLIENT_ID =
ZADF_V_O365CONF-CLIENT_ID .
ZO365_CONFIG-RESOURCE_ID =
ZADF_V_O365CONF-RESOURCE_ID .
ZO365_CONFIG-AAD_INTERFACE_ID =
ZADF_V_O365CONF-AAD_INTERFACE_ID .
    IF SY-SUBRC = 0.
    UPDATE ZO365_CONFIG ##WARN_OK.
    ELSE.
    INSERT ZO365_CONFIG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADF_V_O365CONF-UPD_FLAG,
STATUS_ZADF_V_O365CONF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADF_V_O365CONF.
  SELECT SINGLE * FROM ZO365_CONFIG WHERE
INTERFACE_ID = ZADF_V_O365CONF-INTERFACE_ID .
ZADF_V_O365CONF-MANDT =
ZO365_CONFIG-MANDT .
ZADF_V_O365CONF-INTERFACE_ID =
ZO365_CONFIG-INTERFACE_ID .
ZADF_V_O365CONF-INTERFACE_TYPE =
ZO365_CONFIG-INTERFACE_TYPE .
ZADF_V_O365CONF-SERVICE_TYPE =
ZO365_CONFIG-SERVICE_TYPE .
ZADF_V_O365CONF-IS_TRY =
ZO365_CONFIG-IS_TRY .
ZADF_V_O365CONF-CLIENT_ID =
ZO365_CONFIG-CLIENT_ID .
ZADF_V_O365CONF-RESOURCE_ID =
ZO365_CONFIG-RESOURCE_ID .
ZADF_V_O365CONF-AAD_INTERFACE_ID =
ZO365_CONFIG-AAD_INTERFACE_ID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADF_V_O365CONF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADF_V_O365CONF-INTERFACE_ID TO
ZO365_CONFIG-INTERFACE_ID .
MOVE ZADF_V_O365CONF-MANDT TO
ZO365_CONFIG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZO365_CONFIG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZO365_CONFIG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZO365_CONFIG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZADF_V_RESTDEST.................................*
FORM GET_DATA_ZADF_V_RESTDEST.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZREST_CONFIG WHERE
(VIM_WHERETAB) .
    CLEAR ZADF_V_RESTDEST .
ZADF_V_RESTDEST-MANDT =
ZREST_CONFIG-MANDT .
ZADF_V_RESTDEST-INTERFACE_ID =
ZREST_CONFIG-INTERFACE_ID .
ZADF_V_RESTDEST-DESTINATION =
ZREST_CONFIG-DESTINATION .
<VIM_TOTAL_STRUC> = ZADF_V_RESTDEST.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADF_V_RESTDEST .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADF_V_RESTDEST.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADF_V_RESTDEST-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZREST_CONFIG WHERE
  INTERFACE_ID = ZADF_V_RESTDEST-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZREST_CONFIG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZREST_CONFIG WHERE
  INTERFACE_ID = ZADF_V_RESTDEST-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZREST_CONFIG.
    ENDIF.
ZREST_CONFIG-MANDT =
ZADF_V_RESTDEST-MANDT .
ZREST_CONFIG-INTERFACE_ID =
ZADF_V_RESTDEST-INTERFACE_ID .
ZREST_CONFIG-DESTINATION =
ZADF_V_RESTDEST-DESTINATION .
    IF SY-SUBRC = 0.
    UPDATE ZREST_CONFIG ##WARN_OK.
    ELSE.
    INSERT ZREST_CONFIG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADF_V_RESTDEST-UPD_FLAG,
STATUS_ZADF_V_RESTDEST-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADF_V_RESTDEST.
  SELECT SINGLE * FROM ZREST_CONFIG WHERE
INTERFACE_ID = ZADF_V_RESTDEST-INTERFACE_ID .
ZADF_V_RESTDEST-MANDT =
ZREST_CONFIG-MANDT .
ZADF_V_RESTDEST-INTERFACE_ID =
ZREST_CONFIG-INTERFACE_ID .
ZADF_V_RESTDEST-DESTINATION =
ZREST_CONFIG-DESTINATION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADF_V_RESTDEST USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADF_V_RESTDEST-INTERFACE_ID TO
ZREST_CONFIG-INTERFACE_ID .
MOVE ZADF_V_RESTDEST-MANDT TO
ZREST_CONFIG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZREST_CONFIG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZREST_CONFIG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZREST_CONFIG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZADF_V_SDK_RETRY................................*
FORM GET_DATA_ZADF_V_SDK_RETRY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADF_SDK_RETRY WHERE
(VIM_WHERETAB) .
    CLEAR ZADF_V_SDK_RETRY .
ZADF_V_SDK_RETRY-MANDT =
ZADF_SDK_RETRY-MANDT .
ZADF_V_SDK_RETRY-INTERFACE_ID =
ZADF_SDK_RETRY-INTERFACE_ID .
ZADF_V_SDK_RETRY-AUTH_INTF_ID =
ZADF_SDK_RETRY-AUTH_INTF_ID .
ZADF_V_SDK_RETRY-INTERFACE_TYPE =
ZADF_SDK_RETRY-INTERFACE_TYPE .
ZADF_V_SDK_RETRY-RETRY_FLAG =
ZADF_SDK_RETRY-RETRY_FLAG .
ZADF_V_SDK_RETRY-CLIENT_ID =
ZADF_SDK_RETRY-CLIENT_ID .
ZADF_V_SDK_RETRY-RESOURCE_ID =
ZADF_SDK_RETRY-RESOURCE_ID .
<VIM_TOTAL_STRUC> = ZADF_V_SDK_RETRY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADF_V_SDK_RETRY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADF_V_SDK_RETRY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADF_V_SDK_RETRY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADF_SDK_RETRY WHERE
  INTERFACE_ID = ZADF_V_SDK_RETRY-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZADF_SDK_RETRY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADF_SDK_RETRY WHERE
  INTERFACE_ID = ZADF_V_SDK_RETRY-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADF_SDK_RETRY.
    ENDIF.
ZADF_SDK_RETRY-MANDT =
ZADF_V_SDK_RETRY-MANDT .
ZADF_SDK_RETRY-INTERFACE_ID =
ZADF_V_SDK_RETRY-INTERFACE_ID .
ZADF_SDK_RETRY-AUTH_INTF_ID =
ZADF_V_SDK_RETRY-AUTH_INTF_ID .
ZADF_SDK_RETRY-INTERFACE_TYPE =
ZADF_V_SDK_RETRY-INTERFACE_TYPE .
ZADF_SDK_RETRY-RETRY_FLAG =
ZADF_V_SDK_RETRY-RETRY_FLAG .
ZADF_SDK_RETRY-CLIENT_ID =
ZADF_V_SDK_RETRY-CLIENT_ID .
ZADF_SDK_RETRY-RESOURCE_ID =
ZADF_V_SDK_RETRY-RESOURCE_ID .
    IF SY-SUBRC = 0.
    UPDATE ZADF_SDK_RETRY ##WARN_OK.
    ELSE.
    INSERT ZADF_SDK_RETRY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADF_V_SDK_RETRY-UPD_FLAG,
STATUS_ZADF_V_SDK_RETRY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADF_V_SDK_RETRY.
  SELECT SINGLE * FROM ZADF_SDK_RETRY WHERE
INTERFACE_ID = ZADF_V_SDK_RETRY-INTERFACE_ID .
ZADF_V_SDK_RETRY-MANDT =
ZADF_SDK_RETRY-MANDT .
ZADF_V_SDK_RETRY-INTERFACE_ID =
ZADF_SDK_RETRY-INTERFACE_ID .
ZADF_V_SDK_RETRY-AUTH_INTF_ID =
ZADF_SDK_RETRY-AUTH_INTF_ID .
ZADF_V_SDK_RETRY-INTERFACE_TYPE =
ZADF_SDK_RETRY-INTERFACE_TYPE .
ZADF_V_SDK_RETRY-RETRY_FLAG =
ZADF_SDK_RETRY-RETRY_FLAG .
ZADF_V_SDK_RETRY-CLIENT_ID =
ZADF_SDK_RETRY-CLIENT_ID .
ZADF_V_SDK_RETRY-RESOURCE_ID =
ZADF_SDK_RETRY-RESOURCE_ID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADF_V_SDK_RETRY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADF_V_SDK_RETRY-INTERFACE_ID TO
ZADF_SDK_RETRY-INTERFACE_ID .
MOVE ZADF_V_SDK_RETRY-MANDT TO
ZADF_SDK_RETRY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADF_SDK_RETRY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADF_SDK_RETRY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADF_SDK_RETRY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZREST_V_CONF_MIS................................*
FORM GET_DATA_ZREST_V_CONF_MIS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZREST_CONF_MISC WHERE
(VIM_WHERETAB) .
    CLEAR ZREST_V_CONF_MIS .
ZREST_V_CONF_MIS-MANDT =
ZREST_CONF_MISC-MANDT .
ZREST_V_CONF_MIS-INTERFACE_ID =
ZREST_CONF_MISC-INTERFACE_ID .
ZREST_V_CONF_MIS-METHOD =
ZREST_CONF_MISC-METHOD .
ZREST_V_CONF_MIS-MAX_RETRY =
ZREST_CONF_MISC-MAX_RETRY .
ZREST_V_CONF_MIS-EMAIL_ID =
ZREST_CONF_MISC-EMAIL_ID .
ZREST_V_CONF_MIS-MAIL_BODY_TXT =
ZREST_CONF_MISC-MAIL_BODY_TXT .
ZREST_V_CONF_MIS-RETRY_METHOD =
ZREST_CONF_MISC-RETRY_METHOD .
<VIM_TOTAL_STRUC> = ZREST_V_CONF_MIS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZREST_V_CONF_MIS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZREST_V_CONF_MIS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZREST_V_CONF_MIS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZREST_CONF_MISC WHERE
  INTERFACE_ID = ZREST_V_CONF_MIS-INTERFACE_ID .
    IF SY-SUBRC = 0.
    DELETE ZREST_CONF_MISC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZREST_CONF_MISC WHERE
  INTERFACE_ID = ZREST_V_CONF_MIS-INTERFACE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZREST_CONF_MISC.
    ENDIF.
ZREST_CONF_MISC-MANDT =
ZREST_V_CONF_MIS-MANDT .
ZREST_CONF_MISC-INTERFACE_ID =
ZREST_V_CONF_MIS-INTERFACE_ID .
ZREST_CONF_MISC-METHOD =
ZREST_V_CONF_MIS-METHOD .
ZREST_CONF_MISC-MAX_RETRY =
ZREST_V_CONF_MIS-MAX_RETRY .
ZREST_CONF_MISC-EMAIL_ID =
ZREST_V_CONF_MIS-EMAIL_ID .
ZREST_CONF_MISC-MAIL_BODY_TXT =
ZREST_V_CONF_MIS-MAIL_BODY_TXT .
ZREST_CONF_MISC-RETRY_METHOD =
ZREST_V_CONF_MIS-RETRY_METHOD .
    IF SY-SUBRC = 0.
    UPDATE ZREST_CONF_MISC ##WARN_OK.
    ELSE.
    INSERT ZREST_CONF_MISC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZREST_V_CONF_MIS-UPD_FLAG,
STATUS_ZREST_V_CONF_MIS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZREST_V_CONF_MIS.
  SELECT SINGLE * FROM ZREST_CONF_MISC WHERE
INTERFACE_ID = ZREST_V_CONF_MIS-INTERFACE_ID .
ZREST_V_CONF_MIS-MANDT =
ZREST_CONF_MISC-MANDT .
ZREST_V_CONF_MIS-INTERFACE_ID =
ZREST_CONF_MISC-INTERFACE_ID .
ZREST_V_CONF_MIS-METHOD =
ZREST_CONF_MISC-METHOD .
ZREST_V_CONF_MIS-MAX_RETRY =
ZREST_CONF_MISC-MAX_RETRY .
ZREST_V_CONF_MIS-EMAIL_ID =
ZREST_CONF_MISC-EMAIL_ID .
ZREST_V_CONF_MIS-MAIL_BODY_TXT =
ZREST_CONF_MISC-MAIL_BODY_TXT .
ZREST_V_CONF_MIS-RETRY_METHOD =
ZREST_CONF_MISC-RETRY_METHOD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZREST_V_CONF_MIS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZREST_V_CONF_MIS-INTERFACE_ID TO
ZREST_CONF_MISC-INTERFACE_ID .
MOVE ZREST_V_CONF_MIS-MANDT TO
ZREST_CONF_MISC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZREST_CONF_MISC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZREST_CONF_MISC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZREST_CONF_MISC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
