*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZADF_V_CONFIG...................................*
TABLES: ZADF_V_CONFIG, *ZADF_V_CONFIG. "view work areas
CONTROLS: TCTRL_ZADF_V_CONFIG
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZADF_V_CONFIG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZADF_V_CONFIG.
* Table for entries selected to show on screen
DATA: BEGIN OF ZADF_V_CONFIG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_CONFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_CONFIG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZADF_V_CONFIG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_CONFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_CONFIG_TOTAL.

*...processing: ZADF_V_EVPOLICY.................................*
TABLES: ZADF_V_EVPOLICY, *ZADF_V_EVPOLICY. "view work areas
CONTROLS: TCTRL_ZADF_V_EVPOLICY
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZADF_V_EVPOLICY. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZADF_V_EVPOLICY.
* Table for entries selected to show on screen
DATA: BEGIN OF ZADF_V_EVPOLICY_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_EVPOLICY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_EVPOLICY_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZADF_V_EVPOLICY_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_EVPOLICY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_EVPOLICY_TOTAL.

*...processing: ZADF_V_MI_CONFIG................................*
TABLES: ZADF_V_MI_CONFIG, *ZADF_V_MI_CONFIG. "view work areas
CONTROLS: TCTRL_ZADF_V_MI_CONFIG
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZADF_V_MI_CONFIG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZADF_V_MI_CONFIG.
* Table for entries selected to show on screen
DATA: BEGIN OF ZADF_V_MI_CONFIG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_MI_CONFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_MI_CONFIG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZADF_V_MI_CONFIG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_MI_CONFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_MI_CONFIG_TOTAL.

*...processing: ZADF_V_O365CONF.................................*
TABLES: ZADF_V_O365CONF, *ZADF_V_O365CONF. "view work areas
CONTROLS: TCTRL_ZADF_V_O365CONF
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZADF_V_O365CONF. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZADF_V_O365CONF.
* Table for entries selected to show on screen
DATA: BEGIN OF ZADF_V_O365CONF_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_O365CONF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_O365CONF_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZADF_V_O365CONF_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_O365CONF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_O365CONF_TOTAL.

*...processing: ZADF_V_RESTDEST.................................*
TABLES: ZADF_V_RESTDEST, *ZADF_V_RESTDEST. "view work areas
CONTROLS: TCTRL_ZADF_V_RESTDEST
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZADF_V_RESTDEST. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZADF_V_RESTDEST.
* Table for entries selected to show on screen
DATA: BEGIN OF ZADF_V_RESTDEST_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_RESTDEST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_RESTDEST_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZADF_V_RESTDEST_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_RESTDEST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_RESTDEST_TOTAL.

*...processing: ZADF_V_SDK_RETRY................................*
TABLES: ZADF_V_SDK_RETRY, *ZADF_V_SDK_RETRY. "view work areas
CONTROLS: TCTRL_ZADF_V_SDK_RETRY
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZADF_V_SDK_RETRY. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZADF_V_SDK_RETRY.
* Table for entries selected to show on screen
DATA: BEGIN OF ZADF_V_SDK_RETRY_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_SDK_RETRY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_SDK_RETRY_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZADF_V_SDK_RETRY_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZADF_V_SDK_RETRY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZADF_V_SDK_RETRY_TOTAL.

*...processing: ZREST_V_CONF_MIS................................*
TABLES: ZREST_V_CONF_MIS, *ZREST_V_CONF_MIS. "view work areas
CONTROLS: TCTRL_ZREST_V_CONF_MIS
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZREST_V_CONF_MIS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZREST_V_CONF_MIS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZREST_V_CONF_MIS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZREST_V_CONF_MIS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZREST_V_CONF_MIS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZREST_V_CONF_MIS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZREST_V_CONF_MIS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZREST_V_CONF_MIS_TOTAL.

*.........table declarations:.................................*
TABLES: ZADF_CONFIG                    .
TABLES: ZADF_EHUB_POLICY               .
TABLES: ZADF_MI_CONFIG                 .
TABLES: ZADF_SDK_RETRY                 .
TABLES: ZO365_CONFIG                   .
TABLES: ZREST_CONFIG                   .
TABLES: ZREST_CONF_MISC                .
