PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZO365_CONFIG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZO365_CONFIG-INTERFACE_ID .
    FIELD ZO365_CONFIG-INTERFACE_TYPE .
    FIELD ZO365_CONFIG-SERVICE_TYPE .
    FIELD ZO365_CONFIG-IS_TRY .
    FIELD ZO365_CONFIG-CLIENT_ID .
    FIELD ZO365_CONFIG-RESOURCE_ID .
    FIELD ZO365_CONFIG-AAD_INTERFACE_ID .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZO365_CONFIG-INTERFACE_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
