PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGROUP_VALUES-AUTH_GROUP .
    FIELD ZGROUP_VALUES-AUTH_GRP_DESC .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGROUP_VALUES-AUTH_GROUP .
  module detail_pai.
 endchain.
