PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZREST_MONITOR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZREST_MONITOR-ZMESSAGEID .
    FIELD ZREST_MONITOR-ZUSER .
    FIELD ZREST_MONITOR-RERTYNUM .
    FIELD ZREST_MONITOR-ZMESSAGENUM .
    FIELD ZREST_MONITOR-STATUS .
    FIELD ZREST_MONITOR-REASON .
    FIELD ZREST_MONITOR-METHOD .
    FIELD ZREST_MONITOR-DESTINATION .
    FIELD ZREST_MONITOR-HOST .
    FIELD ZREST_MONITOR-URI .
    FIELD ZREST_MONITOR-INTERFACE_ID .
    FIELD ZREST_MONITOR-CALLING_PROGRAM .
    FIELD ZREST_MONITOR-CALLING_METHOD .
    FIELD ZREST_MONITOR-BUSINESSID .
    FIELD ZREST_MONITOR-MAIL_SENT .
    FIELD ZREST_MONITOR-ZDELETE .
    FIELD ZREST_MONITOR-DELETEUSER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZREST_MONITOR-ZMESSAGEID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
