class ZCX_ADF_MANAGE_INTERFACE_KEY definition
  public
  inheriting from CX_STATIC_CHECK
  create public .

public section.

  constants ZCX_ADF_CONFIG_NOT_FOUND type SOTR_CONC value '000D3A000D181EEA8DA89710700129A6' ##NO_TEXT.
  constants ZCX_ADF_REST_CONFIG_NOT_FOUND type SOTR_CONC value '000D3A000D181EEA8DA8986535E3A9A6' ##NO_TEXT.
  constants ZCX_ADF_IMPORT_FAILED type SOTR_CONC value '000D3A000D181EEA8DAC264196C349A6' ##NO_TEXT.
  constants ZCX_ADF_CON_UPDATE_FAILED type SOTR_CONC value '000D3A000D181EEA8F9F538638BDA9A8' ##NO_TEXT.
  data INTERFACE_ID type ZINTERFACE_ID .

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional
      !INTERFACE_ID type ZINTERFACE_ID optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_ADF_MANAGE_INTERFACE_KEY IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
me->INTERFACE_ID = INTERFACE_ID .
  endmethod.
ENDCLASS.
